### ISSUE TITLE
Create Config.py to accomodate flexible updating

### ISSUE THREAD

**Issue by Cl3tus** [squandor/dynamicTelegramBot#1]
one thing I just had is that i did a new pull of the new code you've pushed, which wipes the config. Logical ofcourse but what i was thinking is making a seperate config file which is not overwritten if you do a new pull from GIT. I suggest creating a new file called config.py

Change the following in the main script:

import config #adding config.py file

########### Config ###############
url = config.url
bot_token = config.bot_token
unames = config.unames
car_location_idx = config.car_location_idx
##################################

the file config.py has only the following content:

########### Config ###############
url = 'http://x.x.x.x:8080'
bot_token = ''
unames = ['',] ## usernames which can use the bot in telegram
car_location_idx = '111' #lat,long
##################################

**Comment by Cl3tus** [comment]
To continue on this, delete the config.py and create this one as create_config.py
[create_config.zip](https://github.com/squandor/dynamicTelegramBot/files/2656699/create_config.zip)

**Comment by squandor** [comment]
fixed this issue in the code, on first run (or if config.ini is removed) the bot will ask you some questions and will write this to an config.ini
