### ISSUE TITLE
BOT token & Username

### ISSUE THREAD

**Issue by karlzre** [squandor/dynamicTelegramBot#2]
Hi, 

I'm trying to use your app.

1)Could you confirm i can use the same bot token as the one i use for notification from domoticz or do i have to create a new BOT ?
2) when you talk about the username is it the one i can create from the telegram app ?

Actually i think i set up everything but when i send a message to do but it didn't react.
On my console i can see it "i'm listening"

**Comment by squandor** [comment]
sorry for my late response didn't saw te question until now. 
You cant use the same token but need to register another one. 
For the username you must set you're own username which you can see in youre settings inside telegram.
